AllCops:
  NewCops: enable
  Exclude:
    - Guardfile
    - db/**/*

require:
  - rubocop-rails

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Naming/PredicateName:
  Exclude:
    - app/models/user.rb