name: push-to-main-branch
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '.tool-versions' # for asdf .tool-versions
          bundler-cache: true
      - name: install dependencies
        run: bundle install
      - name: run linter
        run: bundle exec rubocop
      - name: run tests
        run: bundle exec rspec